### ISSUE TITLE
topology.once的问题

### ISSUE THREAD

**Issue by feidianbo** [demohi/end#7]
/Users/DEO/Documents/end/node_modules/mongodb/lib/db.js:207
    topology.once('error', createListener(self, 'error', self));
             ^
TypeError: undefined is not a function
    at new Db (/Users/DEO/Documents/end/node_modules/mongodb/lib/db.js:207:14)
    at Function.Db (/Users/DEO/Documents/end/node_modules/mongodb/lib/db.js:80:39)
    at Object.End.connect (/Users/DEO/Documents/end/lib/end.js:31:11)
    at Object.End.init (/Users/DEO/Documents/end/lib/end.js:23:10)
    at Object.<anonymous> (/Users/DEO/Documents/end/demo/app.js:13:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

**Comment by demohi** [comment]
Sorry, this project is not maintained.
